# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1a701cd98fcd08dceb317b86b23f08ba24ec0b06cac05efe4c444fb6ca1be84bce2be02032bbfb9ae1a03d53ee205590242a911da3595a1c9c75a6d014257126

test:
  secret_key_base: 2fc8d9011f13c5c2ea1df7cb6cbe738796a74bc149888cdda0fec7dd2fa710af06c75a53f8d969d698cfbdcd6cd98fd8cdb24a576cebf7e86f14a217a0b39e8a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
